var gulp = require('gulp');
var babel = require('gulp-babel');
var header = require('gulp-header');

var banner = ['/**',
    ' * @gaetancovelli/heap',
    ' * Generated by babel.',
    ' * Author: Gaëtan Covelli',
    ' * Last Updated: <%= new Date().toUTCString() %>',
    ' */',
    ''].join('\n');

gulp.task('babel', function() {
  return gulp.src('Heap.js')
    .pipe(babel({presets: ['es2015']}).on('error', handleError))
    .pipe(header(banner))
    .pipe(gulp.dest('dist'))
});

gulp.task('dev', function() {
  gulp.watch('Heap.js', ['babel']);
})

function handleError(err) {
  console.log(err.toString());
  this.emit('end');
}